services:
  - type: web
    name: dsa-naturals
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        path: /*
        destination: /index.html
